# Nixpacks configuration for Backend API
# Nixpacks auto-detects Python and creates venv at /opt/venv
# Railway root directory is set to /backend

[phases.setup]
# Add PostgreSQL for psycopg2-binary compilation
nixPkgs = ['...', 'postgresql']

[start]
# Start FastAPI application
cmd = 'uvicorn app.main:app --host 0.0.0.0 --port $PORT'
