# Nixpacks configuration for Railway
# Since Railway root directory is set to /backend, we don't need cd backend

[phases.setup]
nixPkgs = ['python311', 'python311Packages.pip', 'postgresql']

[phases.install]
cmds = ['pip install -r requirements.txt']

[phases.build]
cmds = []

[start]
cmd = 'uvicorn app.main:app --host 0.0.0.0 --port $PORT'
