# Railway Configuration for Temporal Worker
# Root directory should be set to /backend in service settings

[build]
builder = "NIXPACKS"
nixpacksConfigPath = "nixpacks.worker.toml"

[deploy]
startCommand = "python -m app.temporal.worker"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
