# Railway Configuration
# This file tells Railway to deploy both Backend API and Worker from the same codebase

[build]
builder = "NIXPACKS"
buildCommand = "cd backend && pip install -r requirements.txt"

# Service 1: Backend API
[[services]]
name = "backend"
startCommand = "cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT"

[services.healthcheck]
path = "/health"
timeout = 300
interval = 300

# Service 2: Temporal Worker (runs workflows)
[[services]]
name = "worker"
startCommand = "cd backend && python -u -m app.temporal.worker"

[services.restartPolicy]
type = "ON_FAILURE"
maxRetries = 10
