# Nixpacks configuration for Temporal Worker
# Let Nixpacks auto-detect Python from requirements.txt and .python-version
# It automatically creates venv at /opt/venv and runs pip install

[start]
cmd = "python -m app.temporal.worker"
